const data = [
  {
    date: "2021-11-14",
    title: "css_create-a-koala",
    repo: "https://github.com/SchoolOfCode/css_create-a-koala",
    status: false,
  },
  {
    date: "2021-11-15",
    title: "ConsoleDOM-Workshop",
    repo: "https://github.com/SchoolOfCode/ConsoleDOM-Workshop",
    status: false,
  },
  {
    date: "2021-11-17",
    title: "JS101-workshop",
    repo: "https://github.com/SchoolOfCode/JS101-workshop",
    status: false,
  },
  {
    date: "2021-11-18",
    title: "workshop_js_objects",
    repo: "https://github.com/SchoolOfCode/workshop_js_objects",
    status: false,
  },
  {
    date: "2021-11-18",
    title: "workshop_js_arrays",
    repo: "https://github.com/SchoolOfCode/workshop_js_arrays",
    status: false,
  },
  {
    date: "2021-11-19",
    title: "RockPaperScissors-Hackathon",
    repo: "https://github.com/SchoolOfCode/w1d5_rock-paper-scissors-hackathon-team-38",
    status: false,
  },
  {
    date: "2021-11-24",
    title: "workshop_clock-challenge",
    repo: "https://github.com/SchoolOfCode/workshop_clock-challenge",
    status: false,
  },
  {
    date: "2021-11-24",
    title: "TalkingToServers_Fetch_Workshop",
    repo: "https://github.com/SchoolOfCode/TalkingToServers_Fetch_Workshop",
    status: false,
  },
  {
    date: "2021-11-25",
    title: "workshop_array-methods",
    repo: "https://github.com/SchoolOfCode/workshop_array-methods",
    status: false,
  },
  {
    date: "2021-11-26",
    title: "hackathon_fetch",
    repo: "https://github.com/SchoolOfCode/hackathon_fetch",
    status: false,
  },
  {
    date: "2021-11-28",
    title: "rock-paper-scissors-workshop",
    repo: "https://github.com/SchoolOfCode/rock-paper-scissors-workshop",
    status: false,
  },
  {
    date: "2021-11-29",
    title: "recap_tasks_week-2",
    repo: "https://github.com/SchoolOfCode/recap_tasks_week-2",
    status: false,
  },
  {
    date: "2021-11-30",
    title: "workshops_not-light",
    repo: "https://github.com/SchoolOfCode/workshops_not-light",
    status: false,
  },
  {
    date: "2021-12-02",
    title: "workshops_clone-a-site",
    repo: "https://github.com/School-of-Code-HQ/workshops_clone-a-site",
    status: false,
  },
  {
    date: "2021-12-03",
    title: "recap_ui-ux_week-3",
    repo: "https://github.com/School-of-Code-HQ/recap_ui-ux_week-3",
    status: false,
  },
  {
    date: "2021-12-05",
    title: "hackathon_fetch-recipe-app",
    repo: "https://github.com/SchoolOfCode/w3d5_hackathon_fetch-recipe-app-superduo",
    status: false,
  },
  {
    date: "2021-12-06",
    title: "workshop_node-intro",
    repo: "https://github.com/SchoolOfCode/workshop_node-intro",
    status: false,
  },
  {
    date: "2021-12-08",
    title: "workshops_express-101-books-api",
    repo: "https://github.com/School-of-Code-HQ/workshops_express-101-books-api",
    status: false,
  },
  {
    date: "2021-12-08",
    title: "workshop_RESTful-API-design",
    repo: "https://github.com/SchoolOfCode/workshop_RESTful-API-design",
    status: false,
  },
  {
    date: "2021-12-10",
    title: "hackathon_build-a-backend",
    repo: "https://github.com/SchoolOfCode/hackathon_build-a-backend",
    status: false,
  },
  {
    date: "2021-12-12",
    title: "express-middleware-workshop",
    repo: "https://github.com/SchoolOfCode/express-middleware-workshop",
    status: false,
  },
  {
    date: "2021-12-12",
    title: "recap_node-express_week-4",
    repo: "https://github.com/SchoolOfCode/recap_node-express_week-4",
    status: false,
  },
  {
    date: "2021-12-16",
    title: "workshops_config-management-12-factor-app",
    repo: "https://github.com/SchoolOfCode/workshops_config-management-12-factor-app",
    status: false,
  },
  {
    date: "2021-12-16",
    title: "workshops_node-pg-codealong",
    repo: "https://github.com/SchoolOfCode/workshops_node-pg-codealong",
    status: false,
  },
  {
    date: "2021-12-17",
    title: "hackathon_energiser-score-tracker",
    repo: "https://github.com/SchoolOfCode/hackathon_energiser-score-tracker",
    status: false,
  },
  {
    date: "2021-12-19",
    title: "recap_sql-and-node",
    repo: "https://github.com/SchoolOfCode/recap_sql-and-node",
    status: false,
  },
  {
    date: "2021-12-23",
    title: "workshop_make-your-own-codewars",
    repo: "https://github.com/SchoolOfCode/workshop_make-your-own-codewars",
    status: false,
  },
  {
    date: "2021-01-05",
    title: "workshop_React-useState-pt1",
    repo: "https://github.com/SchoolOfCode/workshop_React-useState-pt1",
    status: false,
  },
  {
    date: "2021-01-05",
    title: "workshop_React-useState-pt2",
    repo: "https://github.com/SchoolOfCode/workshop_React-useState-pt2",
    status: false,
  },

  {
    date: "2021-01-06",
    title: "JS_ImmutableUpdates_Workshop	",
    repo: "https://github.com/SchoolOfCode/w7d3_immutable_updates-team-52-fatou-kattana-marian",
    status: false,
  },
  {
    date: "2021-01-06",
    title: "	workshop_react_lists-and-keys",
    repo: "https://github.com/SchoolOfCode/workshop_react_lists-and-keys",
    status: false,
  },
  {
    date: "2021-01-07",
    title: "w7d4_react-hackathon",
    repo: "https://classroom.github.com/a/_iACviEW",
    status: false,
  },
  {
    date: "2021-01-09",
    title: "recap_react-front-end-blog",
    repo: "https://github.com/SchoolOfCode/recap_react-front-end-blog",
    status: false,
  },
  {
    date: "2021-01-10",
    title: "workshop_first-useEffect",
    repo: "https://github.com/SchoolOfCode/workshop_first-useEffect",
    status: false,
  },
  {
    date: "2021-01-12",
    title: "workshops_react-practice-challenge",
    repo: "https://github.com/SchoolOfCode/workshops_react-practice-challenge",
    status: false,
  },
  {
    date: "2021-01-12",
    title: "workshops_reduce-math-class",
    repo: "https://github.com/SchoolOfCode/workshops_reduce-math-class",
    status: false,
  },
  {
    date: "2021-01-13",
    title: "React_Router_Workshop",
    repo: "https://github.com/SchoolOfCode/React_Router_Workshop",
    status: false,
  },
  {
    date: "2021-01-13",
    title: "workshop_React-testing-library",
    repo: "https://github.com/SchoolOfCode/workshop_React-testing-library",
    status: false,
  },
  {
    date: "2021-01-14",
    title: "hackathon_react-app-with-api-data",
    repo: "https://github.com/SchoolOfCode/hackathon_react-app-with-api-data",
    status: false,
  },
  {
    date: "2021-01-17",
    title: "projects_national-project-week",
    repo: "https://github.com/SchoolOfCode/projects_national-project-week",
    status: false,
  },
];

export default data;
